### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by Arbos** [Arbos/nwn2mdk#1]
# Features for version 1.0

### Collision Mesh 2
- [x] Parse packet
- [x] Export vertices
- [x] Export faces
- [x] Export normals
- [x] Export texture coordinates
- [x] Export material

### Collision Mesh 3
- [x] Parse packet
- [x] Export vertices
- [x] Export faces
- [x] Export normals
- [x] Export texture coordinates
- [x] Export material

### Collision Spheres
- [x] Parse packet
- [x] Export

### Hair
- [x] Parse packet
- [x] Export

### Helm
- [x] Parse packet
- [x] Export

### Hook
- [x] Parse packet
- [x] Export

### Rigid mesh
- [x] Parse packet
- [x] Export vertices
- [x] Export tangents
- [x] Export binormals
- [x] Export texture coordinates
- [x] Export faces
- [x] Export diffuse map
- [x] Export normal map
- [x] Export tint map
- [x] Export glow map
- [x] Export diffuse color
- [x] Export specular color
- [x] Export specular power
- [x] Export specular value
- [x] Export material flags

### Skin
- [x] Parse packet
- [x] Export vertices
- [x] Export tangents
- [x] Export binormals
- [x] Export texture coordinates
- [x] Export faces
- [x] Export diffuse map
- [x] Export normal map
- [x] Export tint map
- [x] Export glow map
- [x] Export diffuse color
- [x] Export specular color
- [x] Export specular power
- [x] Export specular value
- [x] Export material flags
- [x] Export body skinning
- [x] Export head skinning

### Walk mesh
- [x] Parse packet
- [x] Export vertices
- [x] Export faces
- [x] Export material

## GR2 to FBX

- [x] Skeleton
- [x] Animation

### Collision Mesh 2
- [x] Import vertices
- [x] Import faces
- [x] Import material

### Collision Mesh 3
- [x] Import vertices
- [x] Import faces
- [x] Import material

###  Collision Spheres
- [x] Import

### Hair
- [x] Import

### Helm
- [x] Import

### Hook
- [x] Import

### Rigid mesh
- [x] Import vertices
- [x] Import tangents
- [x] Import binormals
- [x] Import texture coordinates
- [x] Import faces
- [x] Import diffuse map
- [x] Import normal map
- [x] Import tint map
- [x] Import glow map
- [x] Import diffuse color
- [x] Import specular color
- [x] Import specular power
- [x] Import specular value
- [x] Import material flags

### Skin
- [x] Import vertices
- [x] Import tangents
- [x] Import binormals
- [x] Import texture coordinates
- [x] Import faces
- [x] Import diffuse map
- [x] Import normal map
- [x] Import tint map
- [x] Import glow map
- [x] Import diffuse color
- [x] Import specular color
- [x] Import specular power
- [x] Import specular value
- [x] Import material flags
- [x] Import body skinning
- [x] Import head skinning

## Walk mesh
- [x] Import

### Skeleton
- [x] Bone position
- [x] Bone orientation
- [x] Bone scale

### Animation
  - [x] Bone position
  - [x] Bone orientation
  - [x] Bone scale

## Others
- [x] Configuration file: NWN2 installation directory
- [x] Automatically extract textures used by a MDB from zip files
- [ ] Test, polish and fix bugs until it's production ready.

**Comment by DolbitNihuya** [comment]
I have an issue that no one bothered to probably report until now;
Why do you need a file nwn2mdk-tmp.fbx that isn't even provided in github??

Importing .mdb causes this error:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\nwn2mdk\__init__.py", line 189, in execute
    bpy.ops.import_scene.fbx(filepath=tmpfbx,
  File "G:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Couldn't open file 'C:\\Users\\user\\Downloads\\te\\nwn2mdk-tmp.fbx' ([Errno 2] No such file or directory: 'C:\\Users\\user\\Downloads\\te\\nwn2mdk-tmp.fbx')

Trust me, I tried using older blender versions, it's the same shit.
